config/routes.rb
Rails.application.routes.draw do
  root 'posts#new'
  # Login
scope '/login' do
  get '/'  => 'sessions#new', as: :login
  get '/error'  => 'sessions#error', as: :login_error
  get '/error/passwd'  => 'sessions#newpass', as: :login_passwd
  get '/session'  => 'sessions#loggedout', as: :login_session
  post '/'  => 'sessions#create'
end
# Logout
scope '/logout' do
  get '/' => 'sessions#destroy', as: :logout
end
# Reset
scope '/reset' do
  get '/' => 'reset#new', as: :reset
  post '/' => 'reset#check'
  get '/error' => 'reset#error', as: :reset_error
  get '/change/error' => 'reset#chgerror', as: :reset_error_reset
  get '/done' => 'reset#done', as: :reset_done
  get '/:id' => 'reset#reset'
  post '/:id' => 'reset#change', as: :reset_reset
end
# Signup
scope '/signup' do
  get '/'  => 'users#new', as: :signup
  get '/error/email'  => 'users#emlerr', as: :emlerr
  get '/error/user'  => 'users#usrerr', as: :usrerr
  post '/'  => 'users#create'
end
# Verify
scope '/verify' do
  get '/' => 'verify#new', as: :verify
  post '/' => 'verify#verify'
  get '/error' => 'verify#error', as: :verify_error
end
# Settings
scope '/settings' do
  get '/' => 'dashboard#settings', as: :settings
  post '/' => 'dashboard#apply'
end
# Write
scope '/write' do
  get '/' => 'posts#write', as: :write
  post '/' => 'posts#post'
  get '/edit/:id' => 'posts#edit', as: :edit
  post '/edit/:id' => 'posts#update', as: :update
end
scope '/manage' do
  get '/' => 'posts#manage', as: :manage
  scope '/links' do
    get '/' => 'dashboard#link', as: :link
    get '/add' => 'dashboard#addlink', as: :addlink
    post '/add' => 'dashboard#linkadd'
    get '/delete/:id' => 'dashboard#dellink', as: :linkdelete
  end
  scope '/menus' do
    get '/' => 'dashboard#menu', as: :menu
    get '/add' => 'dashboard#addmenu', as: :addmenu
    post '/add' => 'dashboard#menuadd'
    get '/delete/:id' => 'dashboard#delmenu', as: :menudelete
  end
  get '/delete/:id' => 'posts#delete', as: :delete
end
# Posts
scope '/posts' do
  get '/', to: redirect('/')
  scope '/:id' do
    get '/' => 'posts#details'
    get '/share' => 'posts#share', as: :share
    post '/comment' => 'posts#comment', as: :comment
    get '/comment/:cid/delete' => 'dashboard#delcomment', as: :delcomment
    get '/:slug' => 'posts#details', as: :post
  end
end
scope '/users' do
  get '/manage' => 'dashboard#usrmgmt', as: :usrmgmt
  get '/make/admin/:id' => 'account#mkadmin', as: :mkadmin
  get '/make/user/:id' => 'account#mkusr', as: :mkusr
  get '/deactivate/:id' => 'account#deactivate', as: :deactivate
  get '/impersonate/:id' => 'account#impersonate', as: :impersonate
  get '/stop-impersonation/:id' => 'account#stop_impersonate', as: :stopimpersonate
end
scope '/comments' do
  get '/moderation' => 'dashboard#moderation', as: :moderationq
  get '/approve/:id' => 'posts#approvecommment', as: :approvecommment
end
get '/category/:id' => 'posts#categories', as: :category
get '/profile/:id' => 'profile#new', as: :profile
get '/category', to: redirect('/')
get '/author-posts', to: redirect('/')
get '/search' => 'posts#search', as: :search
get '/author-posts/:q' => 'posts#author_search', as: :asearch
get '/dash' => 'dashboard#new', as: :dash
scope '/account' do
  get '/' => 'account#profile', as: :account
  post '/' => 'account#update'
end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
before_action :require_user
before_action :check_user
before_action :check_admin
before_action :check_activated
def delcomment
  c = Comment.find_by(id: params[:cid])
  if current_user.id == c.owner || current_user.level == "1"
    c.deleted = "1"
    post = Post.find_by(id: c.post_id)
    post.post_comments = post.post_comments.to_i - 1
    post.save
    if c.save
      redirect_to session[:return_url]+"#"+c.id.to_s
    end
  else
    redirect_to session[:return_url]+"#"+c.id
  end
end
def dellink
  link = Link.find_by(id: params[:id])
  link.delete
  redirect_to link_path
end
def linkadd
  link = Link.new()
  link.title = params[:link][:title]
  link.url = params[:link][:url]
  if link.save
    redirect_to link_path
  end
end
def delmenu
  menu = Menu.find_by(id: params[:id])
  menu.delete
  redirect_to menu_path
end
def menuadd
  menu = Menu.new()
  menu.title = params[:menu][:title]
  menu.subtitle = params[:menu][:subtitle]
  menu.url = params[:menu][:url]
  if menu.save
    redirect_to menu_path
  end
end
def apply
  if Setting.first.nil?
    settings = Setting.new()
    if params[:settings][:blog_name].present?
      settings.blog_name = params[:settings][:blog_name]
    end
      if params[:settings][:blog_email].present?
        settings.blog_email = params[:settings][:blog_email]
      end
        if params[:settings][:blog_tagline].present?
          settings.blog_tagline = params[:settings][:blog_tagline]
        end
          if params[:settings][:blog_twitter].present?
            settings.blog_twitter = params[:settings][:blog_twitter]
          end
            if params[:settings][:blog_facebook].present?
              settings.blog_facebook = params[:settings][:blog_facebook]
            end
              if params[:settings][:blog_about].present?
                settings.blog_about = params[:settings][:blog_about]
              end
              if params[:settings][:blog_appid].present?
                settings.blog_appid = params[:settings][:blog_appid]
              end
              if params[:settings][:blog_css].present?
                settings.blog_css = params[:settings][:blog_css]
              end
              if params[:settings][:blog_logo].present?
                settings.blog_logo = params[:settings][:blog_logo]
              end
              if params[:settings][:recaptcha_public].present?
                settings.recaptcha_public = params[:settings][:recaptcha_public]
              end
              if params[:settings][:recaptcha_private].present?
                settings.recaptcha_private = params[:settings][:recaptcha_private]
              end
              if params[:settings][:blog_css_bg].present?
                settings.blog_css_bg = params[:settings][:blog_css_bg]
              else
                settings.blog_css_bg = '#F4F4F4'
              end
              if params[:settings][:blog_css_header].present?
                settings.blog_css_header = params[:settings][:blog_css_header]
              else
                settings.blog_css_header = '#FFF'
              end
              if params[:settings][:blog_css_tc].present?
                settings.blog_css_tc = params[:settings][:blog_css_tc]
              else
                settings.blog_css_tc = '#000'
              end
              if params[:settings][:blog_css_post].present?
                settings.blog_css_post = params[:settings][:blog_css_post]
              else
                settings.blog_css_post = '#FFF'
              end
              if params[:settings][:blog_css_button].present?
                settings.blog_css_button = params[:settings][:blog_css_button]
              else
                settings.blog_css_button = '#5DBEB3'
              end
              if params[:settings][:blog_css_highlight].present?
                settings.blog_css_highlight = params[:settings][:blog_css_highlight]
              else
                settings.blog_css_highlight = '#2EBAAE'
              end
              if params[:settings][:dash_css_bg].present?
                settings.dash_css_bg = params[:settings][:dash_css_bg]
              else
                settings.dash_css_bg = '#FFF'
              end
              if params[:settings][:dash_css_tc].present?
                settings.dash_css_tc = params[:settings][:dash_css_tc]
              else
                settings.dash_css_tc = '#000'
              end
              if params[:settings][:dash_css_mtc].present?
                settings.dash_css_mtc = params[:settings][:dash_css_mtc]
              else
                settings.dash_css_mtc = '#fff'
              end
              if params[:settings][:dash_css_highlight].present?
                settings.dash_css_highlight = params[:settings][:dash_css_highlight]
              else
                settings.dash_css_highlight = '#F2849E'
              end
    elsif ! Setting.first.nil?
      settings = Setting.first
      if params[:settings][:blog_name].present?
        settings.blog_name = params[:settings][:blog_name]
      end
        if params[:settings][:blog_email].present?
          settings.blog_email = params[:settings][:blog_email]
        end
          if params[:settings][:blog_tagline].present?
            settings.blog_tagline = params[:settings][:blog_tagline]
          end
            if params[:settings][:blog_twitter].present?
              settings.blog_twitter = params[:settings][:blog_twitter]
            end
              if params[:settings][:blog_facebook].present?
                settings.blog_facebook = params[:settings][:blog_facebook]
              end
              if params[:settings][:blog_about].present?
                settings.blog_about = params[:settings][:blog_about]
              end
              if params[:settings][:blog_appid].present?
                settings.blog_appid = params[:settings][:blog_appid]
              end
              if params[:settings][:blog_css_bg].present?
                settings.blog_css_bg = params[:settings][:blog_css_bg]
              end
              if params[:settings][:blog_css_tc].present?
                settings.blog_css_tc = params[:settings][:blog_css_tc]
              end
              if params[:settings][:blog_css_post].present?
                settings.blog_css_post = params[:settings][:blog_css_post]
              end
              if params[:settings][:blog_css_button].present?
                settings.blog_css_button = params[:settings][:blog_css_button]
              end
              if params[:settings][:blog_css_header].present?
                settings.blog_css_header = params[:settings][:blog_css_header]
              end
              if params[:settings][:blog_css_highlight].present?
                settings.blog_css_highlight = params[:settings][:blog_css_highlight]
              end
              if params[:settings][:blog_logo].present?
                settings.blog_logo = params[:settings][:blog_logo]
              end
              if params[:settings][:recaptcha_public].present?
                settings.recaptcha_public = params[:settings][:recaptcha_public]
              end
              if params[:settings][:recaptcha_private].present?
                settings.recaptcha_private = params[:settings][:recaptcha_private]
              end
              if params[:settings][:dash_css_bg].present?
                settings.dash_css_bg = params[:settings][:dash_css_bg]
              end
              if params[:settings][:dash_css_tc].present?
                settings.dash_css_tc = params[:settings][:dash_css_tc]
              end
              if params[:settings][:dash_css_mtc].present?
                settings.dash_css_mtc = params[:settings][:dash_css_mtc]
              end
              if params[:settings][:dash_css_highlight].present?
                settings.dash_css_highlight = params[:settings][:dash_css_highlight]
              end
      end
    if settings.save
      redirect_to settings_path
    end
end
def new
end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/addlink.html.erb
<%= content_for :dash, "1" %>
<%= content_for :title, "Write a post" %>
<!-- Wrapper -->
  <div id="wrapper">
    <%= render 'partials/dash_nav' %>

    <!-- Main -->
      <div id="main">
        <div class="inner">

          <header>
            <h1>Let's add a link!</h1>
          </header>
          <%= form_for(:link, url: addlink_path) do |f| %>
          <div class="field half first">
            <%= f.text_field :title, :placeholder => "Link Title" %>
            </div>
          <div class="field half">
          <%= f.text_field :url, :placeholder => "URL" %>
        </div>
        <br />
          <div class="field half first">
          <%= f.submit "Add", :class => "special" %>
        </div>
          <% end %>
        </div>
      </div>
    </div>
    <%= render "partials/dash_scripts" %>

app/views/dashboard/addmenu.html.erb
<%= content_for :dash, "1" %>
<%= content_for :title, "Write a post" %>
<!-- Wrapper -->
  <div id="wrapper">
    <%= render 'partials/dash_nav' %>

    <!-- Main -->
      <div id="main">
        <div class="inner">

          <header>
            <h1>Adding a menu option is as simple as 1, 2, 3!</h1>
          </header>
          <%= form_for(:profile, url: addmenu_path) do |f| %>
          <div class="field half first">
            <%= f.text_field :title, :placeholder => "Menu Title" %>
            </div>
            <div class="field half">
              <%= f.text_field :subtitle, :placeholder => "Menu Subtitle" %>
              </div>
          <div class="field half first">
          <%= f.text_field :url, :placeholder => "URL" %>
        </div>
        <br />
          <div class="field half">
          <%= f.submit "Add", :class => "special" %>
        </div>
          <% end %>
        </div>
      </div>
    </div>
    <%= render "partials/dash_scripts" %>

app/views/dashboard/link.html.erb
<%= content_for :dash, "1" %>
<%= content_for :title, "Manage Your Posts" %>
<!-- Wrapper -->
  <div id="wrapper">
    <%= render 'partials/dash_nav' %>

    <!-- Main -->
   <div id="main">
     <div class="inner">
       <header>
         <h1>Manage Your Header Links</h1>
         <a href="<%= addlink_path %>"><%= submit_tag "Add", :class => "button special small" %></a>
       </header>
       <br />
       <section>
         <div class="table-wrapper">
           <table class="alt">
             <thead>
               <tr>
                 <th>Title</th>
                 <th>URL</th>
                 <th>Actions</th>
               </tr>
             </thead>
             <tbody>
               <% Link.all.each do |l| %>
               <tr>
                 <th><%= l.title %></th>
                 <th><%= l.url %></th>
                 <th><%= link_to "Remove", linkdelete_path(l.id)%></th>
               </tr>
               <% end %>
             </tbody>
           </table>
         </div>
         <%= render "partials/dash_scripts" %>

app/views/dashboard/menu.html.erb
<%= content_for :dash, "1" %>
<%= content_for :title, "Manage Your Posts" %>
<!-- Wrapper -->
  <div id="wrapper">
    <%= render 'partials/dash_nav' %>

    <!-- Main -->
   <div id="main">
     <div class="inner">
       <header>
         <h1>Manage Your Menu Links</h1>
         <a href="<%= addmenu_path %>"><%= submit_tag "Add", :class => "button special small" %></a>
       </header>
       <br />
       <section>
         <div class="table-wrapper">
           <table class="alt">
             <thead>
               <tr>
                 <th>Title</th>
                 <th>Subtitle</th>
                 <th>URL</th>
                 <th>Actions</th>
               </tr>
             </thead>
             <tbody>
               <% Menu.all.each do |m| %>
               <tr>
                 <th><%= m.title %></th>
                 <th><%= m.subtitle %></th>
                 <th><%= m.url %></th>
                 <th><%= link_to "Remove", menudelete_path(m.id)%></th>
               </tr>
               <% end %>
             </tbody>
           </table>
         </div>
         <%= render "partials/dash_scripts" %>

app/views/dashboard/moderation.html.erb
<%= content_for :dash, "1" %>
<%= content_for :title, "Manage Your Posts" %>
<!-- Wrapper -->
  <div id="wrapper">
    <%= render 'partials/dash_nav' %>

    <!-- Main -->
   <div id="main">
     <div class="inner">
       <header>
         <h1>Comment Moderation Queue</h1>
       </header>
       <br />
       <section>
         <div class="table-wrapper">
           <table class="alt">
             <thead>
               <tr>
                 <th>Comment</th>
                 <th>Date Submitted</th>
                 <th>Submitted By</th>
                 <th>Actions</th>
               </tr>
             </thead>
             <tbody>
               <% Comment.where(:awaiting_moderation => "1", :deleted => "0").pluck(:content, :owner, :created_at, :id, :post_id).reverse.map do |content, owner, created_at, id, post_id| %>
               <tr>
                 <th><%= ActionView::Base.full_sanitizer.sanitize(content) %></th>
                 <th><%= User.find_by(:id => owner).first_name %> <%= User.find_by(:id => owner).last_name %> (<%= User.find_by(:id => owner).email %>)</th>
                 <th><%= created_at.strftime("%B %e, %Y") %></th>
                 <th><%= link_to "View", post_path(post_id, Post.find_by(id: post_id).slug)+"#"+id.to_s %> / <%= link_to "Delete Comment", delcomment_path(post_id, id) %> / <%= link_to "Approve", approvecommment_path(id) %></th>
               </tr>
               <% end %>
             </tbody>
           </table>
         </div>
         <%= render "partials/dash_scripts" %>

app/views/dashboard/new.html.erb
<%= content_for :dash, "1" %>
<%= content_for :title, "Your Dashboard" %>
<!-- Wrapper -->
  <div id="wrapper">
    <%= render 'partials/dash_nav' %>

    <!-- Main -->
      <div id="main">
        <div class="inner">
          <header>
            <h1>Welcome back, <%= current_user.first_name %></h1>
          </header>
          <section class="tiles">
            <article class="style1">
              <span class="image">
                <img src="/images/pic01.jpg" alt="" />
              </span>
              <a href="<%= manage_path %>">
                <h2>Posts</h2>
                <div class="content">
                  <p>Writing a post? Let's go!</p>
                </div>
              </a>
            </article>
            <article class="style2">
              <span class="image">
                <img src="/images/pic02.jpg" alt="" />
              </span>
              <a href="<%= settings_path %>">
                <h2>Settings</h2>
                <div class="content">
                  <p>Set your site details here</p>
                </div>
              </a>
            </article>
            <article class="style1">
              <span class="image">
                <img src="/images/pic03.jpg" alt="" />
              </span>
              <a href="<%= link_path %>">
                <h2>Header Links</h2>
                <div class="content">
                  <p>Here's where you add header links</p>
                </div>
              </a>
            </article>
            <article class="style4">
              <span class="image">
                <img src="/images/pic04.jpg" alt="" />
              </span>
              <a href="<%= menu_path %>">
                <h2>Menu Links</h2>
                <div class="content">
                  <p>Time for some new links?</p>
                </div>
              </a>
            </article>
            <article class="style5">
              <span class="image">
                <img src="/images/pic05.jpg" alt="" />
              </span>
              <a href="<%= usrmgmt_path %>">
                <h2>User Management</h2>
                <div class="content">
                  <p>Need to stalk your users?</p>
                </div>
              </a>
            </article>
            <article class="style6">
              <span class="image">
                <img src="/images/pic06.jpg" alt="" />
              </span>
              <a href="<%= moderationq_path %>">
                <h2>Comment Moderation</h2>
                <div class="content">
                  <p>Comment time!</p>
                </div>
              </a>
            </article>
          </section>
        </div>
      </div>

  </div>
<%= render "partials/dash_scripts" %>

app/views/dashboard/usrmgmt.html.erb
<%= content_for :dash, "1" %>
<%= content_for :title, "Manage Your Posts" %>
<!-- Wrapper -->
  <div id="wrapper">
    <%= render 'partials/dash_nav' %>

    <!-- Main -->
   <div id="main">
     <div class="inner">
       <header>
         <h1>User Management</h1>
       </header>
       <br />
       <section>
         <div class="table-wrapper">
           <table class="alt">
             <thead>
               <tr>
                 <th>First Name</th>
                 <th>Last Name</th>
                 <th>Email</th>
                 <th>Joined</th>
                 <th>Actions</th>
               </tr>
             </thead>
             <tbody>
               <% User.all.reverse_each do |u| %>
               <tr>
                 <th><%= u.first_name %></th>
                 <th><%= u.last_name %></th>
                 <th><%= u.email %></th>
                 <th><%= u.created_at.strftime("%B %e, %Y") %></th>
                 <th><%= link_to "View", profile_path(u.id) %> / <% if u.level == "0" %><%= link_to "Make Admin", mkadmin_path(u.id) %><% else %><%= link_to "Make User", mkusr_path(u.id) %><% end %> / <%= link_to "Deactivate", deactivate_path(u.id) %> / <%= link_to "Impersonate", impersonate_path(u.id) %> / <%= link_to "Stalk", "https://google.com/search?q=#{u.first_name+'+'+u.last_name}", :target => '_new' %></th>
               </tr>
               <% end %>
             </tbody>
           </table>
         </div>
         <%= render "partials/dash_scripts" %>