config/routes.rb
Rails.application.routes.draw do
  root 'posts#new'
  # Login
scope '/login' do
  get '/'  => 'sessions#new', as: :login
  get '/error'  => 'sessions#error', as: :login_error
  get '/error/passwd'  => 'sessions#newpass', as: :login_passwd
  get '/session'  => 'sessions#loggedout', as: :login_session
  post '/'  => 'sessions#create'
end
# Logout
scope '/logout' do
  get '/' => 'sessions#destroy', as: :logout
end
# Reset
scope '/reset' do
  get '/' => 'reset#new', as: :reset
  post '/' => 'reset#check'
  get '/error' => 'reset#error', as: :reset_error
  get '/change/error' => 'reset#chgerror', as: :reset_error_reset
  get '/done' => 'reset#done', as: :reset_done
  get '/:id' => 'reset#reset'
  post '/:id' => 'reset#change', as: :reset_reset
end
# Signup
scope '/signup' do
  get '/'  => 'users#new', as: :signup
  get '/error/email'  => 'users#emlerr', as: :emlerr
  get '/error/user'  => 'users#usrerr', as: :usrerr
  post '/'  => 'users#create'
end
# Verify
scope '/verify' do
  get '/' => 'verify#new', as: :verify
  post '/' => 'verify#verify'
  get '/error' => 'verify#error', as: :verify_error
end
# Settings
scope '/settings' do
  get '/' => 'dashboard#settings', as: :settings
  post '/' => 'dashboard#apply'
end
# Write
scope '/write' do
  get '/' => 'posts#write', as: :write
  post '/' => 'posts#post'
  get '/edit/:id' => 'posts#edit', as: :edit
  post '/edit/:id' => 'posts#update', as: :update
end
scope '/manage' do
  get '/' => 'posts#manage', as: :manage
  scope '/links' do
    get '/' => 'dashboard#link', as: :link
    get '/add' => 'dashboard#addlink', as: :addlink
    post '/add' => 'dashboard#linkadd'
    get '/delete/:id' => 'dashboard#dellink', as: :linkdelete
  end
  scope '/menus' do
    get '/' => 'dashboard#menu', as: :menu
    get '/add' => 'dashboard#addmenu', as: :addmenu
    post '/add' => 'dashboard#menuadd'
    get '/delete/:id' => 'dashboard#delmenu', as: :menudelete
  end
  get '/delete/:id' => 'posts#delete', as: :delete
end
# Posts
scope '/posts' do
  get '/', to: redirect('/')
  scope '/:id' do
    get '/' => 'posts#details'
    get '/share' => 'posts#share', as: :share
    post '/comment' => 'posts#comment', as: :comment
    get '/comment/:cid/delete' => 'dashboard#delcomment', as: :delcomment
    get '/:slug' => 'posts#details', as: :post
  end
end
scope '/users' do
  get '/manage' => 'dashboard#usrmgmt', as: :usrmgmt
  get '/make/admin/:id' => 'account#mkadmin', as: :mkadmin
  get '/make/user/:id' => 'account#mkusr', as: :mkusr
  get '/deactivate/:id' => 'account#deactivate', as: :deactivate
  get '/impersonate/:id' => 'account#impersonate', as: :impersonate
  get '/stop-impersonation/:id' => 'account#stop_impersonate', as: :stopimpersonate
end
scope '/comments' do
  get '/moderation' => 'dashboard#moderation', as: :moderationq
  get '/approve/:id' => 'posts#approvecommment', as: :approvecommment
end
get '/category/:id' => 'posts#categories', as: :category
get '/profile/:id' => 'profile#new', as: :profile
get '/category', to: redirect('/')
get '/author-posts', to: redirect('/')
get '/search' => 'posts#search', as: :search
get '/author-posts/:q' => 'posts#author_search', as: :asearch
get '/dash' => 'dashboard#new', as: :dash
scope '/account' do
  get '/' => 'account#profile', as: :account
  post '/' => 'account#update'
end
end

app/views/partials/_blog.html.erb
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
<!--[if lte IE 8]>
<script src="https://ltscdn.m6.nz/panther/future_imperfect/html5shiv.js"></script>
<![endif]-->
<link rel="stylesheet" href="https://ltscdn.m6.nz/panther/future_imperfect/main.css" />
<!--[if lte IE 9]>
<link rel="stylesheet" href="https://ltscdn.m6.nz/panther/future_imperfect/ie9.css" />
<![endif]-->
<!--[if lte IE 8]>
<link rel="stylesheet" href="https://ltscdn.m6.nz/panther/future_imperfect/ie8.css" />
<![endif]-->

app/views/partials/_blog_footer.html.erb
<!-- Footer -->
  <section id="footer">
    <ul class="icons">
      <% if Setting.limit(1).pluck(:blog_twitter).first %><li><a href="<%= Setting.limit(1).pluck(:blog_twitter).first %>" class="fa-twitter"><span class="label">Twitter</span></a></li><% end %>
      <% if Setting.limit(1).pluck(:blog_facebook).first %><li><a href="<%= Setting.limit(1).pluck(:blog_facebook).first %>" class="fa-facebook"><span class="label">Facebook</span></a></li><% end %>
      <% if Setting.limit(1).pluck(:blog_email).first %><li><a href="mailto:<%= Setting.limit(1).pluck(:blog_email).first %>" class="fa-envelope"><span class="label">Email</span></a></li><% end %>
    </ul>
    <p class="copyright">&copy; <%= Date.today.year %> <%= Setting.limit(1).pluck(:blog_name).first %></p>
  </section>

</section>
</div>

<!-- Scripts -->
<script src="https://ltscdn.m6.nz/panther/future_imperfect/jquery.js"></script>
<script src="https://ltscdn.m6.nz/panther/future_imperfect/skel.js"></script>
<script src="https://ltscdn.m6.nz/panther/future_imperfect/util.js"></script>
<!--[if lte IE 8]>
<script src="https://ltscdn.m6.nz/panther/future_imperfect/respond.js"></script>
<![endif]-->
<script src="https://ltscdn.m6.nz/panther/future_imperfect/main.js"></script>

app/views/partials/_blog_header.html.erb
<!-- Header -->
  <header id="header">
    <h1><a href="<%= root_path %>"><%= Setting.limit(1).pluck(:blog_name).first %></a></h1>
    <nav class="links">
      <ul>
        <% Link.all.each do |l| %>
        <li><a href="<%= l.url %>"><%= l.title %></a></li>
        <% end %>
      </ul>
    </nav>
    <nav class="main">
      <ul>
        <li class="search">
          <a class="fa-search" href="#search">Search</a>
          <form id="search" method="get" action="/search">
            <input type="text" name="q" placeholder="Search" autocomplete="off" />
          </form>
        </li>
        <li class="menu">
          <a class="fa-bars" href="#menu">Menu</a>
        </li>
      </ul>
    </nav>
  </header>

app/views/partials/_blog_menu.html.erb
<!-- Menu -->
  <section id="menu">

    <!-- Search -->
      <section>
        <form class="search" method="get" action="/search">
          <input type="text" name="q" placeholder="Search" autocomplete="off" />
        </form>
      </section>

    <!-- Links -->
      <section>
        <ul class="links">
          <% if current_user %>
          <% if session[:impersonate] %>
          <li>
            <a href="<%= stopimpersonate_path(session[:impersonate]) %>">
              <h3>Stop impersonation</h3>
              <p>Stop impersonating that person you creep</p>
            </a>
          </li><% end %>
          <li>
            <a href="<%= account_path %>">
              <h3>Your Account</h3>
              <p>Manage your account here</p>
            </a>
          </li><% end %>
          <% Menu.all.each do |m| %>
          <li>
            <a href="<%= m.url %>">
              <h3><%= m.title %></h3>
              <p><%= m.subtitle %></p>
            </a>
          </li><% end %>
        </ul>
      </section>

    <!-- Actions -->
      <section>
        <ul class="actions vertical">
          <% if current_user && current_user.level == "1" %>
          <li><a href="<%= dash_path %>" class="button big fit">Dashboard</a></li>
          <% elsif current_user && current_user.level == "0" %>
          <li><a href="<%= logout_path %>" class="button big fit">Log Out</a></li>
          <% else %>
          <li><a href="<%= login_path %>" class="button big fit">Log In</a></li>
          <% end %>
        </ul>
      </section>

  </section>

app/views/partials/_comingsoon.html.erb
<!-- fontawesome -->
<script src="https://use.fontawesome.com/3db7fc1628.js"></script>


<!-- google font -->
<link href='https://fonts.googleapis.com/css?family=Cabin:400,700' rel='stylesheet' type='text/css'>

<!-- custom css -->
<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
<link rel="stylesheet" href="https://ltscdn.m6.nz/panther/coming_soon/main.css" />

app/views/partials/_comingsoon_html.html.erb
<div class="se-pre-con"></div>
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="header-logo-wrapper">
        <%= image_tag "logo-text-white.png", :style => 'height: 150px !important;', :class => 'img-responsive center-block' %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
    <h1 class="text-center">Welcome to Panther!</h1>
    <h3 class="text-center">The site owner probably hasn't set this up yet</h3>
    </div>
  </div>

</div>
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script>
$(window).load(function() {
  // Animate loader off screen
  $(".se-pre-con").fadeOut("slow");
});
</script>

app/views/partials/_comments_recaptcha.html.erb
<% if Setting.limit(1).pluck(:recaptcha_public).first && Setting.limit(1).pluck(:recaptcha_private).first %>
<script>
var submitInvisibleRecaptchaForm = function () {
  $("#write-comment").submit();
};
</script>
<% end %>

app/views/partials/_dash.html.erb
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
<!--[if lte IE 8]>
<script src="https://ltscdn.m6.nz/panther/phantom/html5shiv.js"></script>
<![endif]-->
<link rel="stylesheet" href="https://ltscdn.m6.nz/panther/phantom/main.css" />
<!--[if lte IE 9]>
<link rel="stylesheet" href="https://ltscdn.m6.nz/panther/phantom/ie9.css" />
<![endif]-->
<!--[if lte IE 8]>
<link rel="stylesheet" href="https://ltscdn.m6.nz/panther/phantom/ie8.css" />
<![endif]-->

app/views/partials/_dash_nav.html.erb
    <!-- Header -->
      <header id="header">
        <div class="inner">

          <!-- Logo -->
            <a href="<%= dash_path %>" class="logo">
              <span class="symbol"><img src="/images/logo.svg" alt="" /></span><span class="title">Panther</span>
            </a>

          <!-- Nav -->
            <nav>
              <ul>
                <li><a href="#menu">Menu</a></li>
              </ul>
            </nav>

        </div>
      </header>

    <!-- Menu -->
      <nav id="menu">
        <h2>Menu</h2>
        <ul><% if current_user && current_user.level == "1" %>
          <li><a href="<%= dash_path %>">Home</a></li>
          <li><a href="<%= root_path %>">Visit Your Site</a></li>
          <li><a href="<%= manage_path %>">Post Management</a></li>
          <li><a href="<%= settings_path %>">Site Settings</a></li>
          <li><a href="<%= account_path %>">Your Account</a></li>
          <li><a href="<%= logout_path %>">Logout</a></li>
          <% if session[:impersonate] %>
          <li><a href="<%= stopimpersonate_path(session[:impersonate]) %>">Stop Impersonation</a>
            <% end %>
          <% else %>
          <li><a href="<%= root_path %>">Home</a></li>
          <li><a href="<%= account_path %>">Your Account</a></li>
          <% end %>
        </ul>
      </nav>

app/views/partials/_dash_scripts.html.erb
  <!-- Scripts -->
  <script src="https://ltscdn.m6.nz/panther/phantom/jquery.js"></script>
  <script src="https://ltscdn.m6.nz/panther/phantom/skel.js"></script>
  <script src="https://ltscdn.m6.nz/panther/phantom/util.js"></script>
  <!--[if lte IE 8]>
  <script src="https://ltscdn.m6.nz/panther/phantom/respond.js"></script>
  <![endif]-->
  <script src="https://ltscdn.m6.nz/panther/phantom/main.js"></script>

app/views/partials/_login_recaptcha.html.erb
<% if Setting.limit(1).pluck(:recaptcha_public).first && Setting.limit(1).pluck(:recaptcha_private).first %>
<script src="https://ltscdn.m6.nz/panther/future_imperfect/jquery.js"></script>
<script>
var submitInvisibleRecaptchaForm = function () {
  $(".vertical-form").submit();
};
</script>
<% end %>

app/views/partials/_profile.html.erb
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<!--[if lte IE 8]>
<script src="https://ltscdn.m6.nz/panther/identity/html5shiv.js"></script>
<![endif]-->
<link rel="stylesheet" href="https://ltscdn.m6.nz/panther/identity/main.css" />
<!--[if lte IE 9]>
<link rel="stylesheet" href="https://ltscdn.m6.nz/panther/identity/ie9.css" />
<![endif]-->
<!--[if lte IE 8]>
<link rel="stylesheet" href="https://ltscdn.m6.nz/panther/identity/ie8.css" />
<![endif]-->
<noscript><link rel="stylesheet" href="https://ltscdn.m6.nz/panther/identity/noscript.css" /></noscript>

app/views/partials/_profile_footer.html.erb
<footer>
  <ul class="icons">
    <% if ! User.find_by(id: params[:id]).twitter.nil? %><li><a href="<%= User.find_by(id: params[:id]).facebook %>" class="fa-facebook">Facebook</a></li><% end %>
    <% if ! User.find_by(id: params[:id]).twitter.nil? %><li><a href="<%= "https://twitter.com/"+User.find_by(id: params[:id]).twitter %>" class="fa-twitter">Twitter</a></li><% end %>
  </ul>
</footer>
</section>

<!-- Footer -->
<footer id="footer">
<ul class="copyright">
  <li>&copy; <%= Date.today.year %> <%= Setting.limit(1).pluck(:blog_name).first %></li>
</ul>
</footer>

app/views/partials/_profile_scripts.html.erb
<!-- Scripts -->
  <!--[if lte IE 8]><script src="https://ltscdn.m6.nz/panther/identity/respond.min.js"></script><![endif]-->
  <script>
    if ('addEventListener' in window) {
      window.addEventListener('load', function() { document.body.className = document.body.className.replace(/\bis-loading\b/, ''); });
      document.body.className += (navigator.userAgent.match(/(MSIE|rv:11\.0)/) ? ' is-ie' : '');
    }
  </script>