config/routes.rb
Rails.application.routes.draw do
  root 'posts#new'
  # Login
scope '/login' do
  get '/'  => 'sessions#new', as: :login
  get '/error'  => 'sessions#error', as: :login_error
  get '/error/passwd'  => 'sessions#newpass', as: :login_passwd
  get '/session'  => 'sessions#loggedout', as: :login_session
  post '/'  => 'sessions#create'
end
# Logout
scope '/logout' do
  get '/' => 'sessions#destroy', as: :logout
end
# Reset
scope '/reset' do
  get '/' => 'reset#new', as: :reset
  post '/' => 'reset#check'
  get '/error' => 'reset#error', as: :reset_error
  get '/change/error' => 'reset#chgerror', as: :reset_error_reset
  get '/done' => 'reset#done', as: :reset_done
  get '/:id' => 'reset#reset'
  post '/:id' => 'reset#change', as: :reset_reset
end
# Signup
scope '/signup' do
  get '/'  => 'users#new', as: :signup
  get '/error/email'  => 'users#emlerr', as: :emlerr
  get '/error/user'  => 'users#usrerr', as: :usrerr
  post '/'  => 'users#create'
end
# Verify
scope '/verify' do
  get '/' => 'verify#new', as: :verify
  post '/' => 'verify#verify'
  get '/error' => 'verify#error', as: :verify_error
end
# Settings
scope '/settings' do
  get '/' => 'dashboard#settings', as: :settings
  post '/' => 'dashboard#apply'
end
# Write
scope '/write' do
  get '/' => 'posts#write', as: :write
  post '/' => 'posts#post'
  get '/edit/:id' => 'posts#edit', as: :edit
  post '/edit/:id' => 'posts#update', as: :update
end
scope '/manage' do
  get '/' => 'posts#manage', as: :manage
  scope '/links' do
    get '/' => 'dashboard#link', as: :link
    get '/add' => 'dashboard#addlink', as: :addlink
    post '/add' => 'dashboard#linkadd'
    get '/delete/:id' => 'dashboard#dellink', as: :linkdelete
  end
  scope '/menus' do
    get '/' => 'dashboard#menu', as: :menu
    get '/add' => 'dashboard#addmenu', as: :addmenu
    post '/add' => 'dashboard#menuadd'
    get '/delete/:id' => 'dashboard#delmenu', as: :menudelete
  end
  get '/delete/:id' => 'posts#delete', as: :delete
end
# Posts
scope '/posts' do
  get '/', to: redirect('/')
  scope '/:id' do
    get '/' => 'posts#details'
    get '/share' => 'posts#share', as: :share
    post '/comment' => 'posts#comment', as: :comment
    get '/comment/:cid/delete' => 'dashboard#delcomment', as: :delcomment
    get '/:slug' => 'posts#details', as: :post
  end
end
scope '/users' do
  get '/manage' => 'dashboard#usrmgmt', as: :usrmgmt
  get '/make/admin/:id' => 'account#mkadmin', as: :mkadmin
  get '/make/user/:id' => 'account#mkusr', as: :mkusr
  get '/deactivate/:id' => 'account#deactivate', as: :deactivate
  get '/impersonate/:id' => 'account#impersonate', as: :impersonate
  get '/stop-impersonation/:id' => 'account#stop_impersonate', as: :stopimpersonate
end
scope '/comments' do
  get '/moderation' => 'dashboard#moderation', as: :moderationq
  get '/approve/:id' => 'posts#approvecommment', as: :approvecommment
end
get '/category/:id' => 'posts#categories', as: :category
get '/profile/:id' => 'profile#new', as: :profile
get '/category', to: redirect('/')
get '/author-posts', to: redirect('/')
get '/search' => 'posts#search', as: :search
get '/author-posts/:q' => 'posts#author_search', as: :asearch
get '/dash' => 'dashboard#new', as: :dash
scope '/account' do
  get '/' => 'account#profile', as: :account
  post '/' => 'account#update'
end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :password, length: { minimum: 8 }, allow_nil: false, on: :create
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  def emlerr
    @user = User.new
  end
  def usrerr
    @user = User.new
  end
def create
  @user = User.new(user_params)
  if User.exists?(:email => @user.email)
    redirect_to emlerr_path
  else
    if verify_recaptcha(model: @user, secret_key: Setting.limit(1).pluck(:recaptcha_private).first)
    if EmailValidator.valid?(@user.email)
      if User.first.nil?
        act_code = SecureRandom.hex(6)
        token = SecureRandom.hex(48)
        @user.activation_code = act_code
        @user.activated = '0'
        @user.level = '1'
        @user.enabled = '1'
        if @user.save
          PostmarkMailer.verify(@user).deliver_now
          session[:user_id] = @user.id
          redirect_to dash_path
        else
          redirect_to emlerr_path
        end
      else
          act_code = SecureRandom.hex(6)
          token = SecureRandom.hex(48)
          @user.activation_code = act_code
          @user.activated = '0'
          @user.level = '0'
          @user.enabled = '1'
          if @user.save
            PostmarkMailer.verify(@user).deliver_now
            session[:user_id] = @user.id
            redirect_to dash_path
          else
            redirect_to emlerr_path
          end
      end
  end
end
end
end
  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/emlerr.html.erb
<% content_for :title, "Sign Up" %>
<% content_for :font, "https://fonts.googleapis.com/css?family=Montserrat:200" %>
<% content_for :stylesheet, "https://ltscdn.m6.nz/panther/stylesheets/login.css" %>
<% content_for :login, "1" %>
<ul class="notice errors">
<li>Whoops! Somebody's already used that email</li>
</ul>
<a href="<%= root_path %>"><%= image_tag "logo-text-white.png", :height => '55', :class => 'logo' %></a> <!-- 180^2 for signup -->

<%= form_for(@user, url: signup_path, :html => {:class => 'vertical-form'}) do |f| %>
<legend>
Sign Up
</legend>
<%= f.text_field :first_name, :placeholder => "First name", :type => 'text' %>
<%= f.text_field :last_name, :placeholder => "Last name" %>
<%= f.email_field :email, :placeholder => "Email" %>
<%= f.password_field :password, :placeholder => "Password", :pattern => ".{8,}" %>
   <% if Setting.limit(1).pluck(:recaptcha_public).first && Setting.limit(1).pluck(:recaptcha_private).first %><%= invisible_recaptcha_tags site_key: Setting.limit(1).pluck(:recaptcha_public).first, callback: 'submitInvisibleRecaptchaForm', text: "Sign Up", :theme => 'dark' %><% else %><%= f.submit "Sign Up" %><% end %>
   <p><a href="<%= login_path %>">Log in?</a></p>
	 <% end %>
<%= render 'partials/login_recaptcha' %>

app/views/users/new.html.erb
<% content_for :title, "Sign Up" %>
<% content_for :font, "https://fonts.googleapis.com/css?family=Montserrat:200" %>
<% content_for :stylesheet, "https://ltscdn.m6.nz/panther/stylesheets/login.css" %>
<% content_for :login, "1" %>

<a href="<%= root_path %>"><%= image_tag "logo-text-white.png", :height => '55', :class => 'logo' %></a> <!-- 180^2 for signup -->

<%= form_for(@user, url: signup_path, :html => {:class => 'vertical-form'}) do |f| %>
<legend>
Sign Up
</legend>
<%= f.text_field :first_name, :placeholder => "First name", :type => 'text' %>
<%= f.text_field :last_name, :placeholder => "Last name" %>
<%= f.email_field :email, :placeholder => "Email" %>
<%= f.password_field :password, :placeholder => "Password (min 8 characters)", :pattern => ".{8,}" %>
<% if Setting.limit(1).pluck(:recaptcha_public).first && Setting.limit(1).pluck(:recaptcha_private).first %><%= invisible_recaptcha_tags site_key: Setting.limit(1).pluck(:recaptcha_public).first, callback: 'submitInvisibleRecaptchaForm', text: "Sign Up", :theme => 'dark' %><% else %><%= f.submit "Sign Up" %><% end %>
<p><a href="<%= login_path %>">Log in?</a></p>
	 <% end %>
<%= render 'partials/login_recaptcha' %>

app/views/users/usrerr.html.erb
<% content_for :title, "Sign Up" %>
<% content_for :font, "https://fonts.googleapis.com/css?family=Montserrat:200" %>
<% content_for :stylesheet, "https://ltscdn.m6.nz/panther/stylesheets/login.css" %>
<% content_for :login, "1" %>
<ul class="notice errors">
<li>Uh Oh! Your name contains profanity. Please try again</li>
</ul>
<a href="<%= root_path %>"><%= image_tag "logo-text-white.png", :height => '55', :class => 'logo' %></a> <!-- 180^2 for signup -->

<%= form_for(@user, url: signup_path, :html => {:class => 'vertical-form'}) do |f| %>
<legend>
Sign Up
</legend>
<%= f.text_field :first_name, :placeholder => "First name", :type => 'text' %>
<%= f.text_field :last_name, :placeholder => "Last name" %>
<%= f.email_field :email, :placeholder => "Email" %>
<%= f.password_field :password, :placeholder => "Password", :pattern => ".{8,}" %>
<% if Setting.limit(1).pluck(:recaptcha_public).first && Setting.limit(1).pluck(:recaptcha_private).first %><%= invisible_recaptcha_tags site_key: Setting.limit(1).pluck(:recaptcha_public).first, callback: 'submitInvisibleRecaptchaForm', text: "Sign Up", :theme => 'dark' %><% else %><%= f.submit "Sign Up" %><% end %>
   <p><a href="<%= login_path %>">Log in?</a></p>
	 <% end %>
<%= render 'partials/login_recaptcha' %>