config/routes.rb
Rails.application.routes.draw do
  root 'posts#new'
  # Login
scope '/login' do
  get '/'  => 'sessions#new', as: :login
  get '/error'  => 'sessions#error', as: :login_error
  get '/error/passwd'  => 'sessions#newpass', as: :login_passwd
  get '/session'  => 'sessions#loggedout', as: :login_session
  post '/'  => 'sessions#create'
end
# Logout
scope '/logout' do
  get '/' => 'sessions#destroy', as: :logout
end
# Reset
scope '/reset' do
  get '/' => 'reset#new', as: :reset
  post '/' => 'reset#check'
  get '/error' => 'reset#error', as: :reset_error
  get '/change/error' => 'reset#chgerror', as: :reset_error_reset
  get '/done' => 'reset#done', as: :reset_done
  get '/:id' => 'reset#reset'
  post '/:id' => 'reset#change', as: :reset_reset
end
# Signup
scope '/signup' do
  get '/'  => 'users#new', as: :signup
  get '/error/email'  => 'users#emlerr', as: :emlerr
  get '/error/user'  => 'users#usrerr', as: :usrerr
  post '/'  => 'users#create'
end
# Verify
scope '/verify' do
  get '/' => 'verify#new', as: :verify
  post '/' => 'verify#verify'
  get '/error' => 'verify#error', as: :verify_error
end
# Settings
scope '/settings' do
  get '/' => 'dashboard#settings', as: :settings
  post '/' => 'dashboard#apply'
end
# Write
scope '/write' do
  get '/' => 'posts#write', as: :write
  post '/' => 'posts#post'
  get '/edit/:id' => 'posts#edit', as: :edit
  post '/edit/:id' => 'posts#update', as: :update
end
scope '/manage' do
  get '/' => 'posts#manage', as: :manage
  scope '/links' do
    get '/' => 'dashboard#link', as: :link
    get '/add' => 'dashboard#addlink', as: :addlink
    post '/add' => 'dashboard#linkadd'
    get '/delete/:id' => 'dashboard#dellink', as: :linkdelete
  end
  scope '/menus' do
    get '/' => 'dashboard#menu', as: :menu
    get '/add' => 'dashboard#addmenu', as: :addmenu
    post '/add' => 'dashboard#menuadd'
    get '/delete/:id' => 'dashboard#delmenu', as: :menudelete
  end
  get '/delete/:id' => 'posts#delete', as: :delete
end
# Posts
scope '/posts' do
  get '/', to: redirect('/')
  scope '/:id' do
    get '/' => 'posts#details'
    get '/share' => 'posts#share', as: :share
    post '/comment' => 'posts#comment', as: :comment
    get '/comment/:cid/delete' => 'dashboard#delcomment', as: :delcomment
    get '/:slug' => 'posts#details', as: :post
  end
end
scope '/users' do
  get '/manage' => 'dashboard#usrmgmt', as: :usrmgmt
  get '/make/admin/:id' => 'account#mkadmin', as: :mkadmin
  get '/make/user/:id' => 'account#mkusr', as: :mkusr
  get '/deactivate/:id' => 'account#deactivate', as: :deactivate
  get '/impersonate/:id' => 'account#impersonate', as: :impersonate
  get '/stop-impersonation/:id' => 'account#stop_impersonate', as: :stopimpersonate
end
scope '/comments' do
  get '/moderation' => 'dashboard#moderation', as: :moderationq
  get '/approve/:id' => 'posts#approvecommment', as: :approvecommment
end
get '/category/:id' => 'posts#categories', as: :category
get '/profile/:id' => 'profile#new', as: :profile
get '/category', to: redirect('/')
get '/author-posts', to: redirect('/')
get '/search' => 'posts#search', as: :search
get '/author-posts/:q' => 'posts#author_search', as: :asearch
get '/dash' => 'dashboard#new', as: :dash
scope '/account' do
  get '/' => 'account#profile', as: :account
  post '/' => 'account#update'
end
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_user, except: [:details, :new, :author_search, :categories, :share, :search]
  before_action :check_user, except: [:details, :new, :author_search, :categories, :share, :search]
  before_action :check_admin, except: [:details, :new, :author_search, :categories, :share, :comment, :search]
  before_action :check_activated, except: [:details, :new, :author_search, :categories, :share, :search]
  def search
    if params[:q].nil?
      redirect_to root_path
    end
  end
  def new
    session[:return_url] = nil
  end
  def approvecommment
    comment = Comment.find_by(id: params[:id])
    comment.awaiting_moderation = "0"
    if comment.save
      redirect_to moderationq_path
    end
  end
  def comment
    comment = Comment.new()
    comment.owner = current_user.id
    comment.deleted = "0"
    comment.awaiting_moderation = "0"
    if params[:comment][:content].present?
      comment.content = params[:comment][:content]
    end
    if ! comment.content.nil?
    comment.post_id = params[:id]
    post = Post.find_by(id: params[:id])
    post.post_comments = post.post_comments.to_i + 1
    post.save
    if comment.save
      url = session[:return_url]+"#"+comment.id.to_s
      redirect_to url
    end
else
  redirect_to session[:return_url]
end
  end
  def share
    post = Post.find_by(id: params[:id])
    post.post_shares = post.post_shares.to_i + 1
    post.save
  end
  def update
    post = Post.find_by(id: params[:id])
    if params[:write][:title].present?
      post.post_title = params[:write][:title]
    end
    if params[:write][:subtitle].present?
      post.post_subtitle = params[:write][:subtitle]
    end
    if params[:write][:content].present?
      post.post_body = params[:write][:content]
    end
    if params[:write][:tags].present?
      post.post_category = params[:write][:tags]
    end
    if params[:write][:title].present?
      post.slug = params[:write][:title].parameterize
    end
    if post.save
      redirect_to manage_path
    end
    end
  def delete
    post = Post.find_by(id: params[:id])
    post.delete
    redirect_to manage_path
  end
  def post
    post = Post.new()
    post.owner = current_user.id
    if params[:write][:title].present?
      post.post_title = params[:write][:title]
    else
      post.post_title = "I forgot the post title!"
    end
    if params[:write][:subtitle].present?
      post.post_subtitle = params[:write][:subtitle]
    end
    if params[:write][:content].present?
      post.post_body = params[:write][:content]
    else
      post.post_body = "...and body content"
    end
    if params[:write][:tags].present?
      post.post_category = params[:write][:tags]
    end
    if params[:write][:title].present?
      post.slug = params[:write][:title].parameterize
    else
      post.slug = "forgot-the-title"
    end
    if post.save
      redirect_to manage_path
    end
  end
  def details
    if Post.first.nil?
      if Post.first.nil? && params[:id].present?
        redirect_to root_path
      else
      redirect_to '/404'
    end
    elsif ! Post.find_by(id: params[:id]).nil?
      if params[:slug].nil?
        redirect_to post_path(params[:id], Post.find_by(id: params[:id]).slug)
      end
      if params[:slug] && params[:slug] != Post.find_by(id: params[:id]).slug
        redirect_to post_path(params[:id], Post.find_by(id: params[:id]).slug)
      end
      post = Post.find_by(id: params[:id])
      post.post_views = Post.find_by(id: params[:id]).post_views.to_i + 1
      post.save
      session[:return_url] = request.url

    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/author_search.html.erb
<% if Post.first.nil? %>
<% content_for :coming_soon, "1" %>
<% content_for :title, "Coming Soon" %>
<%= render 'partials/comingsoon_html' %>
<% else %>
<% content_for :blog, "1" %>
<% content_for :title, "Home" %>
<!-- Wrapper -->
  <div id="wrapper">

    <%= render 'partials/blog_header' %>
        <%= render 'partials/blog_menu' %>
    <!-- Main -->
      <div id="main">
          <% Post.order('id DESC').where("owner = ?", params[:q]).each do |post| %>
          <!-- Post -->
            <article class="post">
              <header>
                <div class="title">
                  <h2><a href="<%= post_path(post.id, post.slug) %>"><%= post.post_title %></a></h2>
                  <p><%= post.post_subtitle %></p>
                </div>
                <div class="meta">
                  <time class="published" datetime="<%= post.created_at.strftime("%F") %>"><%= post.created_at.strftime("%B %e, %Y") %></time>
                  <a href="<%= asearch_path(post.owner) %>" class="author"><span class="name"><%= User.find_by(id: Post.limit(1).pluck(:owner).first).first_name %></span><img src="<%= gravatar_url(User.find_by(id: Post.limit(1).pluck(:owner).first).email, 200) %>" alt="" /></a>
                </div>
              </header>
              <p><%= raw markdown(post.post_body.truncate_words(25)) %></p>
              <footer>
                <ul class="actions">
                  <li><a href="<%= post_path(post.id, post.slug) %>" class="button big">Continue Reading</a></li>
                </ul>
                <ul class="stats">
                  <li><% if post.post_category.present?
                    post.post_category.split(',').each do |c| %><a href="<%= category_path(c.strip) %>"><%= c %></a> <% end %><% end %></li>
                    <li><a href="javascript:void(0)" class="icon fa-eye"><%= post.post_views.to_i - 1  %></a></li>
                    <li><a href="javascript:void(0)" class="icon fa-comment"><%= post.post_comments.to_i %></a></li>
                    <li><a href="javascript:void(0)" target="popup" onclick="FB.ui({method: 'share',href: '<%= post_url(post.id, post.slug) %>',}, function(response){if(response && ! response.error_message){$.get('<%=share_path(post.id)%>');}});" class="icon fa-share"><%= post.post_shares.to_i  %></a></li>
                </ul>
              </footer>
            </article>
            <% end %>
          </section>

          <%= render 'partials/blog_footer' %>

  <% end %>

app/views/posts/categories.html.erb
<% if Post.first.nil? %>
<% content_for :coming_soon, "1" %>
<% content_for :title, "Coming Soon" %>
<%= render 'partials/comingsoon_html' %>
<% else %>
<% content_for :blog, "1" %>
<% content_for :title, "Home" %>
<!-- Wrapper -->
  <div id="wrapper">

  <%= render 'partials/blog_header' %>
      <%= render 'partials/blog_menu' %>
    <!-- Main -->
      <div id="main">
          <% Post.order('id ASC').where("post_category ~ ?", params[:id]).each do |post| %>
          <!-- Post -->
            <article class="post">
              <header>
                <div class="title">
                  <h2><a href="<%= post_path(post.id, post.slug) %>"><%= post.post_title %></a></h2>
                  <p><%= post.post_subtitle %></p>
                </div>
                <div class="meta">
                  <time class="published" datetime="<%= post.created_at.strftime("%F") %>"><%= post.created_at.strftime("%B %e, %Y") %></time>
                  <a href="<%= asearch_path(post.owner) %>" class="author"><span class="name"><%= User.find_by(id: Post.limit(1).pluck(:owner).first).first_name %></span><img src="<%= gravatar_url(User.find_by(id: Post.limit(1).pluck(:owner).first).email, 200) %>" alt="" /></a>
                </div>
              </header>
              <p><%= raw markdown(post.post_body.truncate_words(25)) %></p>
              <footer>
                <ul class="actions">
                  <li><a href="<%= post_path(post.id, post.slug) %>" class="button big">Continue Reading</a></li>
                </ul>
                <ul class="stats">
                  <li><% if post.post_category.present?
                    post.post_category.split(',').each do |c| %><a href="<%= category_path(c.strip) %>"><%= c %></a> <% end %><% end %></li>
                    <li><a href="javascript:void(0)" class="icon fa-eye"><%= post.post_views.to_i - 1  %></a></li>
                    <li><a href="javascript:void(0)" class="icon fa-comment"><%= post.post_comments.to_i %></a></li>
                    <li><a href="javascript:void(0)" target="popup" onclick="FB.ui({method: 'share',href: '<%= post_url(post.id, post.slug) %>',}, function(response){if(response && ! response.error_message){$.get('<%=share_path(post.id)%>');}});" class="icon fa-share"><%= post.post_shares.to_i  %></a></li>
                </ul>
              </footer>
            </article>
            <% end %>
          </section>

<%= render 'partials/blog_footer' %>

  <% end %>

app/views/posts/details.html.erb
<% if Post.first.nil? %>
<% content_for :coming_soon, "1" %>
<% content_for :title, "Coming Soon" %>
<%= render 'partials/comingsoon_html' %>
<% else %>
<% content_for :blog, "1" %>
<% content_for :single, "1" %>
<% content_for :title, Post.find_by(id: params[:id]).post_title %>
<!-- Wrapper -->
  <div id="wrapper">

<%= render 'partials/blog_header' %>
      <%= render 'partials/blog_menu' %>
    <!-- Main -->
      <div id="main">

        <!-- Post -->
          <article class="post">
            <header>
              <div class="title">
                <h2><a href="<%= request.url %>"><%= Post.find_by(id: params[:id]).post_title %></a></h2>
                <p><%= Post.find_by(id: params[:id]).post_subtitle %></p>
              </div>
              <div class="meta">
                <time class="published" datetime="<%= Post.find_by(id: params[:id]).created_at.strftime("%F") %>"><%= Post.find_by(id: params[:id]).created_at.strftime("%B %e, %Y") %></time>
                <a href="<%= asearch_path(Post.find_by(id: params[:id]).owner) %>" class="author"><span class="name"><%= User.find_by(id: Post.find_by(id: params[:id]).owner).first_name %></span><img src="<%= gravatar_url(User.find_by(id: Post.find_by(id: params[:id]).owner).email, 200) %>" alt="" /></a>
              </div>
            </header>
            <%= raw markdown(Post.find_by(id: params[:id]).post_body) %>
            <footer>
              <ul class="stats">
                <li><% if Post.find_by(id: params[:id]).post_category.present?
                  Post.find_by(id: params[:id]).post_category.split(',').each do |c| %><a href="<%= category_path(c.strip) %>"><%= c %></a> <% end %><% end %></li>
                <li><a href="javascript:void(0)" class="icon fa-eye"><%= Post.find_by(id: params[:id]).post_views.to_i - 1  %></a></li>
                <li><a href="javascript:void(0)" onclick="$('#comment-section').slideToggle();" class="icon fa-comment"><%= Post.find_by(id: params[:id]).post_comments.to_i  %></a></li>
                <li><a href="javascript:void(0)" target="popup" onclick="FB.ui({method: 'share',href: '<%= request.url%>',}, function(response){if(response && ! response.error_message){$.get('<%=share_path(:id)%>');}});" class="icon fa-share"><%= Post.find_by(id: params[:id]).post_shares.to_i  %></a></li>
              </ul>
            </footer>
          </article>

          <article class="post" style="display: none" id="comment-section">
            <% if current_user %>
            <a href="javascript:void(0)" onclick="$('#write-comment').slideToggle();" class="button special small">Comment</a><br /><br />
            <i>Warning: comments may be disturbing, proceed at your own risk</i><br /><br />
            <article class="post" style="display: none" id="write-comment">
              <%= form_for(:comment, url: comment_path(params[:id])) do |f| %>
              <%= f.text_area :content, :class => "editor", :placeholder => "Write your comment here! GitHub flavored makdown is supported" %>
              <br />
              <div class="field half">
                <%= f.submit "Post" %>
            </div>
              <% end %>
            </article>
            <% else %>
            <a href="<%= login_path %>" class="button special small">Comment</a><br /><br />
            <i>Warning: comments may be disturbing, proceed at your own risk</i><br /><br />
            <% end %>
            <% Comment.where(:post_id => params[:id]).pluck(:content, :owner, :created_at, :id, :deleted, :awaiting_moderation).reverse.map do |content, owner, created_at, id, deleted, awaiting_moderation| %>
            <div class="talk-bubble tri-right btm-right" id="<%= id %>">
              <div class="talktext">
                <% if deleted == "0" && awaiting_moderation == "0" %><%= raw markdown(ActionController::Base.helpers.sanitize(content)) %><% elsif deleted == "1" %><p><i>This comment has been deleted</i></p><% elsif deleted == "2"%><p><i>This comment has been marked as spam</i></p><% elsif awaiting_moderation == "1"%><p><i>This comment is awaiting moderation</i></p><% end %>
              </div>
            </div>
            <span class="comment-author"><% if current_user && current_user.id == owner || current_user && current_user.level == "1" %><% if deleted == "0" %><%= link_to "Delete?", delcomment_path(params[:id], id) %> |<% end%><% end%> From <a href="<%= profile_path(owner) %>"><%= User.find_by(id: owner).first_name %><% if User.find_by(id: owner).enabled == "0" %> (Banned)<%end%></a> at <%= created_at.strftime("%l:%M%P on %B %e, %Y") %></span>
            <br />
            <hr>
            <% end %>
          </article>

      </div>
<%= render 'partials/blog_footer' %>
<%= render 'partials/comments_recaptcha' %>
<script>
if(window.location.hash) {
  console.log(window.location.hash)
  $('#comment-section').slideDown();
  $('html, body').animate({
        scrollTop: $(window.location.hash).offset().top
    }, 2000);
}
</script>
  <% end %>

app/views/posts/manage.html.erb
<%= content_for :dash, "1" %>
<%= content_for :title, "Manage Your Posts" %>
<!-- Wrapper -->
  <div id="wrapper">
    <%= render 'partials/dash_nav' %>

    <!-- Main -->
   <div id="main">
     <div class="inner">
       <header>
         <h1>Manage Your Posts</h1>
         <a href="<%= write_path %>"><%= submit_tag "Write", :class => "button special small" %></a>
       </header>
       <br />
       <section>
         <div class="table-wrapper">
           <table class="alt">
             <thead>
               <tr>
                 <th>Title</th>
                 <th>Date Written</th>
                 <th>Quick Analytics</th>
                 <th>Actions</th>
               </tr>
             </thead>
             <tbody>
               <% Post.all.reverse_each do |post| %>
               <tr>
                 <th><%= post.post_title %></th>
                 <th><%= post.created_at.strftime("%B %e, %Y") %></th>
                 <th><a href="javascript:void(0)" class="icon fa-eye"> <%= post.post_views.to_i  %></a>,&nbsp;&nbsp; <a href="javascript:void(0)" class="icon fa-comment"> <%= post.post_comments.to_i %></a>,&nbsp;&nbsp; <a href="javascript:void(0)" class="icon fa-share"> <%= post.post_shares.to_i  %></a></th>
                 <th><%= link_to "View", post_path(post.id, post.slug) %> / <%= link_to "Edit", edit_path(post.id)%> / <%= link_to "Remove", delete_path(post.id)%></th>
               </tr>
               <% end %>
             </tbody>
           </table>
         </div>
         <%= render "partials/dash_scripts" %>

app/views/posts/new.html.erb
<% if Post.first.nil? %>
<% content_for :coming_soon, "1" %>
<% content_for :title, "Coming Soon" %>
<%= render 'partials/comingsoon_html' %>
<% else %>
<% content_for :blog, "1" %>
<% content_for :title, "Home" %>
<!-- Wrapper -->
  <div id="wrapper">
    <%= render 'partials/blog_header' %>
      <%= render 'partials/blog_menu' %>
    <!-- Main -->
      <div id="main">

        <!-- Post -->
          <article class="post">
            <header>
              <div class="title">
                <h2><a href="<%= post_path(Post.order('id DESC').limit(1).pluck(:id).first, Post.limit(1).pluck(:slug).first) %>"><%= Post.order('id DESC').limit(1).pluck(:post_title).first %></a></h2>
                <p><%= Post.order('id DESC').limit(1).pluck(:post_subtitle).first %></p>
              </div>
              <div class="meta">
                <time class="published" datetime="<%= Post.order('id DESC').limit(1).pluck(:created_at).first.strftime("%F") %>"><%= Post.order('id DESC').limit(1).pluck(:created_at).first.strftime("%B %e, %Y") %></time>
                <a href="<%= asearch_path(Post.order('id DESC').limit(1).pluck(:owner).first)%>" class="author"><span class="name"><%= User.find_by(id: Post.order('id DESC').limit(1).pluck(:owner).first).first_name %></span><img src="<%= gravatar_url(User.find_by(id: Post.order('id DESC').limit(1).pluck(:owner).first).email, 200) %>" alt="" /></a>
              </div>
            </header>
            <p><%= raw markdown(Post.order('id DESC').limit(1).pluck(:post_body).first.truncate_words(25)) %></p>
            <footer>
              <ul class="actions">
                <li><a href="<%= post_path(Post.order('id DESC').limit(1).pluck(:id).first, Post.order('id DESC').limit(1).pluck(:slug).first) %>" class="button big">Continue Reading</a></li>
              </ul>
              <ul class="stats">
                <li><% if Post.order('id DESC').limit(1).pluck(:post_category).first.present?
                  Post.order('id DESC').limit(1).pluck(:post_category).first.split(',').each do |c| %><a href="<%= category_path(c.strip) %>"><%= c %></a> <% end %><% end %></li>
                  <li><a href="javascript:void(0)" class="icon fa-eye"><%= Post.order('id DESC').limit(1).pluck(:post_views).first.to_i - 1  %></a></li>
                  <li><a href="javascript:void(0)" class="icon fa-comment"><%= Post.order('id DESC').limit(1).pluck(:post_comments).first.to_i %></a></li>
                  <li><a href="javascript:void(0)" target="popup" onclick="FB.ui({method: 'share',href: '<%= post_url(Post.order('id DESC').limit(1).pluck(:id).first, Post.order('id DESC').limit(1).pluck(:slug).first) %>',}, function(response){if(response && ! response.error_message){$.get('<%=share_path(Post.order('id DESC').limit(1).pluck(:id))%>');}});" class="icon fa-share"><%= Post.order('id DESC').limit(1).pluck(:post_shares).first.to_i  %></a></li>
              </ul>
            </footer>
          </article>
          <% Post.all.order("id DESC").limit(3).offset(1).each do |post| %>
          <!-- Post -->
            <article class="post">
              <header>
                <div class="title">
                  <h2><a href="<%= post_path(post.id, post.slug) %>"><%= post.post_title %></a></h2>
                  <p><%= post.post_subtitle %></p>
                </div>
                <div class="meta">
                  <time class="published" datetime="<%= post.created_at.strftime("%F") %>"><%= post.created_at.strftime("%B %e, %Y") %></time>
                  <a href="<%= asearch_path(post.owner) %>" class="author"><span class="name"><%= User.find_by(id: Post.limit(1).pluck(:owner).first).first_name %></span><img src="<%= gravatar_url(User.find_by(id: Post.limit(1).pluck(:owner).first).email, 200) %>" alt="" /></a>
                </div>
              </header>
              <p><%= raw markdown(post.post_body.truncate_words(25)) %></p>
              <footer>
                <ul class="actions">
                  <li><a href="<%= post_path(post.id, post.slug) %>" class="button big">Continue Reading</a></li>
                </ul>
                <ul class="stats">
                  <li><% if post.post_category.present?
                    post.post_category.split(',').each do |c| %><a href="<%= category_path(c.strip) %>"><%= c %></a> <% end %><% end %></li>
                    <li><a href="javascript:void(0)" class="icon fa-eye"><%= post.post_views.to_i - 1  %></a></li>
                    <li><a href="javascript:void(0)" class="icon fa-comment"><%= post.post_comments.to_i %></a></li>
                    <li><a href="javascript:void(0)" target="popup" onclick="FB.ui({method: 'share',href: '<%= post_url(post.id, post.slug) %>',}, function(response){if(response && ! response.error_message){$.get('<%=share_path(post.id)%>');}});" class="icon fa-share"><%= post.post_shares.to_i  %></a></li>
                </ul>
              </footer>
            </article>
            <% end %>

            					</div>

            				<!-- Sidebar -->
            					<section id="sidebar">

            						<!-- Intro -->
            							<section id="intro">
                            <% if Setting.first.nil? || Setting.limit(1).pluck(:blog_logo).first.nil? %>
            								<a href="<%= root_path %>" class="logo"><img src="images/logo-text-black.png" alt="" /><br /></a>
                            <% else %>
                            <a href="<%= root_path %>" class="logo"><img src="<%= Setting.limit(1).pluck(:blog_logo).first %>" alt="" /><br /></a>
                            <% end %>
            								<header>
            									<h2><%= Setting.limit(1).pluck(:blog_name).first %></h2>
            									<p><%= Setting.limit(1).pluck(:blog_tagline).first %></p>
            								</header>
            							</section>

            						<!-- Mini Posts -->
            							<section>
            								<div class="mini-posts">
                              <% Post.all.offset(3).limit(3).each do |post| %>
            									<!-- Mini Post -->
            										<article class="mini-post">
            											<header>
            												<h3><a href="<%= post_path(post.id, post.slug) %>"><%= post.post_title %></a></h3>
            												<time class="published" datetime="<%= post.created_at.strftime("%F") %>"><%= post.created_at.strftime("%B %e, %Y") %></time>
            												<a href="<%= asearch_path %>?q=<%=post.owner%>" class="author"><img src="images/avatar.jpg" alt="" /></a>
            											</header>
            										</article>
                                <% end %>
            								</div>
            							</section>

            						<!-- About -->
            							<section class="blurb">
            								<h2>About</h2>
            								<p><%= Setting.limit(1).pluck(:blog_about).first %></p>
            								<ul class="actions">
            									<!--<li><a href="#" class="button">Learn More</a></li>-->
            								</ul>
            							</section>

<%= render 'partials/blog_footer' %>


  <% end %>

app/views/posts/search.html.erb
<% if Post.first.nil? %>
<% content_for :coming_soon, "1" %>
<% content_for :title, "Coming Soon" %>
<%= render 'partials/comingsoon_html' %>
<% else %>
<% content_for :blog, "1" %>
<% content_for :title, "Home" %>
<!-- Wrapper -->
  <div id="wrapper">

    <%= render 'partials/blog_header' %>
        <%= render 'partials/blog_menu' %>
    <!-- Main -->
      <div id="main">
          <% Post.order('id DESC').where("lower(post_title) ~ ?", params[:q].downcase).each do |post| %>
          <!-- Post -->
            <article class="post">
              <header>
                <div class="title">
                  <h2><a href="<%= post_path(post.id, post.slug) %>"><%= post.post_title %></a></h2>
                  <p><%= post.post_subtitle %></p>
                </div>
                <div class="meta">
                  <time class="published" datetime="<%= post.created_at.strftime("%F") %>"><%= post.created_at.strftime("%B %e, %Y") %></time>
                  <a href="<%= asearch_path(post.owner) %>" class="author"><span class="name"><%= User.find_by(id: Post.limit(1).pluck(:owner).first).first_name %></span><img src="<%= gravatar_url(User.find_by(id: Post.limit(1).pluck(:owner).first).email, 200) %>" alt="" /></a>
                </div>
              </header>
              <p><%= raw markdown(post.post_body.truncate_words(25)) %></p>
              <footer>
                <ul class="actions">
                  <li><a href="<%= post_path(post.id, post.slug) %>" class="button big">Continue Reading</a></li>
                </ul>
                <ul class="stats">
                  <li><% post.post_category.split(',').each do |c| %><a href="<%= category_path(c.strip) %>"><%= c %></a> <% end %></li>
                  <li><a href="javascript:void(0)" class="icon fa-eye"><%= post.post_views.to_i - 1  %></a></li>
                  <li><a href="javascript:void(0)" class="icon fa-comment"><%= post.post_comments.to_i %></a></li>
                  <li><a href="javascript:void(0)" target="popup" onclick="FB.ui({method: 'share',href: '<%= post_url(post.id, post.slug) %>',}, function(response){if(response && ! response.error_message){$.get('<%=share_path(post.id)%>');}});" class="icon fa-share"><%= post.post_shares.to_i  %></a></li>
                </ul>
              </footer>
            </article>
            <% end %>
          </section>

          <%= render 'partials/blog_footer' %>

  <% end %>